name: manpage

on:
  push:
    branches:
      - master

jobs:
  manpage:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Go modules
        run: go mod download

      - name: Build
        run: go build -v -tags mango

      - name: Generate man-page
        run: ./duf > duf.1

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "docs: update man page"
          branch: master
          commit_user_name: mango ðŸ¤–
          commit_user_email: actions@github.com
          commit_author: mango ðŸ¤– <actions@github.com>
